const DEFAULTS={message:"Hoje é um daqueles dias que merecem ser guardados no coração. Que essa nova fase venha com muita felicidade, amor, saúde, conquistas e motivos para sorrir. Feliz aniversário, Zanny! 💕",signature:"quem te ama muito 💗",date:""};
const get=(k,d)=>localStorage.getItem(k)??d;
function load(){document.getElementById("mainMessage").textContent=get("zanny_message",DEFAULTS.message);document.getElementById("signature").textContent=get("zanny_signature",DEFAULTS.signature);document.getElementById("messageInput").value=get("zanny_message",DEFAULTS.message);document.getElementById("signatureInput").value=get("zanny_signature",DEFAULTS.signature);document.getElementById("dateInput").value=get("zanny_date",DEFAULTS.date);renderGallery();startCountdown();}
function openAdmin(){document.getElementById("adminModal").classList.add("show");document.getElementById("adminModal").setAttribute("aria-hidden","false");}
function closeAdmin(){document.getElementById("adminModal").classList.remove("show");document.getElementById("adminModal").setAttribute("aria-hidden","true");}
function login(){const p=document.getElementById("adminPassword").value;if(p==="zanny2026"){document.getElementById("loginView").hidden=true;document.getElementById("panelView").hidden=false}else alert("Senha incorreta!");}
function logout(){document.getElementById("loginView").hidden=false;document.getElementById("panelView").hidden=true;document.getElementById("adminPassword").value="";}
function saveSettings(){localStorage.setItem("zanny_message",document.getElementById("messageInput").value);localStorage.setItem("zanny_signature",document.getElementById("signatureInput").value);localStorage.setItem("zanny_date",document.getElementById("dateInput").value);const files=[...document.getElementById("photoInput").files];if(files.length){const old=JSON.parse(get("zanny_photos","[]"));Promise.all(files.map(file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)}))).then(imgs=>{localStorage.setItem("zanny_photos",JSON.stringify([...old,...imgs]));document.getElementById("photoInput").value="";load();alert("Tudo salvo! 💗");})}else{load();alert("Alterações salvas! 💗");}}
function renderGallery(){const g=document.getElementById("gallery"),e=document.getElementById("emptyGallery");g.innerHTML="";const photos=JSON.parse(get("zanny_photos","[]"));e.hidden=photos.length>0;photos.forEach((src,i)=>{const d=document.createElement("div");d.className="photo";d.innerHTML=`<img src="${src}" alt="Memória ${i+1}" loading="lazy">`;d.onclick=()=>openLightbox(src);g.appendChild(d)})}
function clearPhotos(){if(confirm("Apagar todas as fotos desta homenagem?")){localStorage.removeItem("zanny_photos");renderGallery();}}
function openLightbox(src){document.getElementById("lightboxImg").src=src;document.getElementById("lightbox").classList.add("show")}
function closeLightbox(){document.getElementById("lightbox").classList.remove("show")}
function startCountdown(){const date=get("zanny_date","");const box=document.getElementById("countdown");if(!date){return}const tick=()=>{const target=new Date(date+"T00:00:00");let diff=target-new Date();if(diff<0){box.querySelectorAll("b").forEach(x=>x.textContent="00");return}const d=Math.floor(diff/86400000);diff%=86400000;const h=Math.floor(diff/3600000);diff%=3600000;const m=Math.floor(diff/60000);const s=Math.floor((diff%60000)/1000);[d,h,m,s].forEach((v,i)=>box.children[i].querySelector("b").textContent=String(v).padStart(2,"0"))};tick();clearInterval(window.cd);window.cd=setInterval(tick,1000)}
function launchConfetti(){for(let i=0;i<35;i++){const x=document.createElement("div");x.textContent=["🎉","💗","✨","🎀","🌸"][Math.floor(Math.random()*5)];x.style.position="fixed";x.style.left=Math.random()*100+"vw";x.style.top="-30px";x.style.fontSize=(15+Math.random()*20)+"px";x.style.zIndex=80;x.style.transition=`transform ${2+Math.random()*2}s linear,opacity 2s`;document.body.appendChild(x);requestAnimationFrame(()=>x.style.transform=`translateY(${innerHeight+80}px) rotate(${Math.random()*700-350}deg)`);setTimeout(()=>x.remove(),4200)}}
setInterval(()=>{const h=document.createElement("div");h.className="heart";h.textContent=["♥","♡","✦"][Math.floor(Math.random()*3)];h.style.left=Math.random()*100+"vw";h.style.fontSize=(12+Math.random()*18)+"px";h.style.color="#f28ab3";h.style.animationDuration=(5+Math.random()*5)+"s";document.getElementById("hearts").appendChild(h);setTimeout(()=>h.remove(),10000)},900);
document.addEventListener("DOMContentLoaded",load);